// This file is generated by Blog Manager. Do not edit manually.

export type Project = {
  id: string;
  name: string;
  description: string;
  icon: string;
  githubUrl: string;
  tags: string[];
};

export const projectsData: Project[] = [
  {
    id: "personalblogweb-manager",
    name: "个人博客与本地内容管理系统",
    githubUrl: "https://github.com/itsR0LL/personalBlogweb",
    description:
      "基于 XinghuisamaBlogs 的非商业二次开发。后续重构了公开站与本地管理端、自建 IPv6 Docker 部署、内容热发布、AI 小助理、天气组件、音乐可播放性校验和发布控制台。这个项目重点展示工程化改造、部署链路、安全边界与内容工作流。",
    icon: "BLOG",
    tags: ["二次开发", "Next.js", "FastAPI", "Docker", "内容热发布", "AI 助手", "自建部署"],
  },
  {
    id: "python-qqbot-voxmind",
    name: "PythonQQBot / VoxMind",
    githubUrl: "https://gitee.com/muchuan114514/just-qqbot.git",
    description:
      "从 QQbot 原型演进而来的 QQ 群舆情与情绪分析平台，围绕消息采集、话题识别、情绪趋势、群关系可视化和报告生成构建。前端使用 React，后端使用 Python / FastAPI，并接入 LLOneBot 与 AI 分析能力。",
    icon: "AI",
    tags: ["原创项目", "React", "FastAPI", "Python", "LLOneBot", "AI 分析", "数据可视化"],
  },
  {
    id: "mytv-cs-platform",
    name: "MYTV 赛事管理平台",
    githubUrl: "https://gitee.com/muchuan114514/mymajor-cs-web.git",
    description:
      "面向绵阳 Major CS 赛事的赛事管理平台，覆盖赛事信息、队伍与选手、赛程、对阵、后台管理和数据展示。项目重点在全栈业务建模、赛事流程整理和面向比赛运营的后台工具设计。",
    icon: "CS",
    tags: ["原创项目", "Nuxt", "Vue", "TypeScript", "Node.js", "赛事管理", "全栈"],
  },
];
